--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02-12-2017 15:46:31
-- Server version: 5.7.19-log
-- Client version: 4.1
--


--
-- Definition for database rhc
--
DROP DATABASE IF EXISTS rhc;
CREATE DATABASE IF NOT EXISTS rhc
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE rhc;

--
-- Definition for table rhc_alcohol_levels
--
CREATE TABLE IF NOT EXISTS rhc_alcohol_levels (
  rhc_id INT(11) NOT NULL AUTO_INCREMENT,
  rhc_device_serial_number VARCHAR(50) NOT NULL,
  rhc_alcohol_level INT(11) NOT NULL,
  PRIMARY KEY (rhc_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Definition for procedure AlcoholLevelDataManagement_public_sp_createAlocholLevelRecord
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE AlcoholLevelDataManagement_public_sp_createAlocholLevelRecord(
  IN vDeviceSerialNumber varchar(50),
  IN vAlcoholLevelData int(11),
  OUT vOperationStatus int(11))
BEGIN
  -- Unanticipated exception
  DECLARE Exit HANDLER FOR SQLEXCEPTION
  set vOperationStatus= getStatusCode('UNKNOWNERROR');

  -- Null Checks
  if isnull(vDeviceSerialNumber) and length(vDeviceSerialNumber) then
    set vOperationStatus= getStatusCode('DEVICESERIALNULL');
  end if;

  if isnull(vAlcoholLevelData) then
    set vOperationStatus= getStatusCode('ALCOHOLLEVELNULL');
  end if;

-- Insert alcohol level data
INSERT INTO rhc_alcohol_levels (rhc_device_serial_number, rhc_alcohol_level)
  VALUES (vDeviceSerialNumber, vAlcoholLevelData);

  set vOperationStatus= getStatusCode('OPERATIONSUCCESSFULL');

END
$$

--
-- Definition for function getStatusCode
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION getStatusCode(statusString varchar(128))
  RETURNS int(11)
BEGIN

if statusString = 'OPERATIONSUCCESSFULL' 
then
    return 1;
elseif statusString = 'UNKNOWNERROR' 
then
    return -1;
elseif statusString = 'DEVICESERIALNULL' 
then
    return -2;
elseif statusString = 'ALCOHOLLEVELNULL' 
then
    return -3;
else
    return - 1;
end
if;
END
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;