--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02-12-2017 09:41:10
-- Server version: 5.7.19-log
-- Client version: 4.1
--


--
-- Definition for database rhc
--
DROP DATABASE IF EXISTS rhc;
CREATE DATABASE IF NOT EXISTS rhc
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE rhc;

--
-- Definition for table rhc_alcohol_levels
--
CREATE TABLE IF NOT EXISTS rhc_alcohol_levels (
  rhc_id INT(11) NOT NULL AUTO_INCREMENT,
  rhc_device_serial_number VARCHAR(50) NOT NULL,
  rhc_alcohol_level INT(11) NOT NULL,
  PRIMARY KEY (rhc_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table rhc_alcohol_levels
--

-- Table rhc.rhc_alcohol_levels does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;